
grpc:
  client:
    tea_weed_server:
      host:
      - ${LOCAL-GRPC-HOST:127.0.0.1}
      port:
      - 6007
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    bamboo_server:
      host:
      - ${LOCAL-GRPC-HOST:127.0.0.1}
      port:
      - 6006
      enableKeepAlive: true
      keepAliveWithoutCalls: true
---
# 上传文件总的最大值
spring:
  servlet:
    multipart:
      max-request-size:
        10MB
# 单个文件的最大值
---
spring:
  servlet:
    multipart:
      max-file-size:
        10MB
---
spring:
  datasource:
    url: jdbc:mysql:///tea_weeds?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username : root
    password : 46132205092017
    driverClassName : com.mysql.cj.jdbc.Driver
---
#JPA Configuration:
spring :
  jpa:
    database : mysql
# Show or not log for each sql query
    show-sql : false
    generate-ddl : true
# Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto : update
#spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy : org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view : true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true